import FormStore from "../store/FormStore";
import Condition, { ICondition } from "./condition";
import { IFieldProps, IComponentProps, IFieldStorage, IFieldRuntimeProps } from "./field.properties";
import Validator from "./validator";
import { IValidationRule } from "./validation";
import { IFieldOptions } from "./field.options";
import { IFormItemLayoutOptions } from './form.properties';
declare class Field implements IFieldProps, IFieldRuntimeProps {
    readonly _type: string;
    id: string;
    name: string;
    uuid: string;
    type: string;
    label: string;
    value: any;
    touched: boolean;
    inputType: string;
    helpText: string;
    placeholder: string;
    fieldOptions: IFieldOptions;
    children: any;
    condition: Condition;
    storage: IFieldStorage;
    store: FormStore;
    location: any;
    conditionState: boolean;
    validator: Validator;
    validation: IValidationRule;
    componentProps: IComponentProps;
    itemLayoutOptions: IFormItemLayoutOptions;
    _dispose: any;
    mergeUpdate(data: Partial<IFieldProps>): void;
    initialize(data: IFieldProps, store: FormStore): void;
    readonly className: string;
    readonly isTouched: boolean;
    readonly isValidateable: boolean;
    readonly isValid: boolean;
    readonly isHidden: boolean;
    readonly isRequired: boolean;
    readonly currentValue: any;
    readonly isDisabled: boolean;
    setValue(value: any): void;
    setTouched(): void;
    setConditionState(value: boolean): void;
    setCondition(condition: ICondition): void;
    validate(): void;
    readonly serialize: string;
    constructor(data: IFieldProps, store: FormStore);
}
export default Field;
